### ISSUE TITLE
js 함수 오류... 

### ISSUE THREAD

**Issue by beom1843** [beom1843/NDERP#7]
jQuery.Deferred exception: staffInfoService.getDept is not a function TypeError: staffInfoService.getDept is not a function
    at getCode (http://localhost:8081/staff_input_form:81:20)
    at HTMLDocument.<anonymous> (http://localhost:8081/staff_input_form:79:3)
    at e (https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:30005)
    at t (https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js:2:30307) undefined

**Comment by beom1843** [comment]
우선 REST CONTROLLER 대신 일반 controller, model을 이용하여 전달하는 것으로 변경함

**Comment by beom1843** [comment]
js 파일의 즉시실행함수 구문을 지키지 않음 ㅠㅠㅠㅠ

var service = (function(){})**()**

**Comment by beom1843** [comment]
+var service 안에 함수 정의만 하고, return에 포함시키지 않음
